"""
Real instruction-tuning data: the Alpaca dataset (~52K instruction-following
examples generated by Stanford's team, permissively licensed for research),
reformatted into this repo's <|user|>/<|assistant|> chat template and
tokenized with the extended tokenizer (vocab_size=50262).

This is what actually teaches broad conversational/instruction-following
behavior -- chat/prepare_chat_synthetic.py's few hundred templated patterns
only cover turn-taking and calculator delegation, not real dialogue variety.

Requires: pip install datasets
Produces data/chat_alpaca/train.bin and val.bin.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
from datasets import load_dataset

from chat.format import format_turn
from tools.tokenizer import get_extended_tokenizer

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "chat_alpaca")


def build_user_message(example) -> str:
    if example.get("input"):
        return f"{example['instruction']}\n\n{example['input']}"
    return example["instruction"]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--val_fraction", type=float, default=0.02)
    p.add_argument("--seed", type=int, default=1337)
    args = p.parse_args()

    enc = get_extended_tokenizer()
    dataset = load_dataset("tatsu-lab/alpaca")["train"]
    split_dataset = dataset.train_test_split(test_size=args.val_fraction, seed=args.seed)
    split_dataset["val"] = split_dataset.pop("test")

    os.makedirs(OUT_DIR, exist_ok=True)
    for name, dset in split_dataset.items():
        ids = []
        for example in dset:
            user_msg = build_user_message(example)
            text = format_turn(user_msg, example["output"])
            ids.extend(enc.encode(text, allowed_special="all"))
        arr = np.array(ids, dtype=np.uint16)
        out_path = os.path.join(OUT_DIR, f"{name}.bin")
        arr.tofile(out_path)
        print(f"{name}: {len(dset):,} examples, {len(ids):,} tokens -> {out_path}")


if __name__ == "__main__":
    main()
